---@type LazySpec
return {
  'tpope/vim-fugitive',
  lazy = false,
  cmd = { 'G', 'Git' },
  ctxmap = {
    {
      ctx = 'cmd.start(lhs, map) and abbr.trigger(" ")',
      mode = 'ca',
      { 'gau', 'Git add --update' },
      { 'gst', 'Git status' },
      { 'gco', 'Git checkout' },
      { 'gad', 'Git add' },
      { 'cad', 'Git cfg add' },
      { 'gau', 'Git add --update' },
      { 'gaup', 'Git add --update --patch' },
    },
    {
      ctx = 'cmd.start',
      mode = 'ca',
      { 'gd', 'botright Gvdiffsplit!' },
      { 'gau', 'Git add --update %' },
      { 'gst', 'Git status <C-r>=expand("%:h")<Cr>' },
      { 'gpl', 'Git pull' },
      { 'gps', 'Git push' },
      { 'gcim', "Git commit -m ''<Left>", eat = '%s' },
      { 'gco', 'Git checkout %' },
      { 'gad', 'Git add %' },
      { 'cad', 'Git cfg add %' },
      { 'gau', 'Git add --update %' },
      { 'gaup', 'Git add --update --patch %' },
      clear = false,
    },
  },
}
